name: Continuous Integration

on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
  MQTT_URL: mqtt://localhost
  MQTT_USER: user
  MQTT_PASS: pass
  WIFI_SSID: ssid
  WIFI_PASS: pass

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check --color always
          - command: clippy
            args: --all-targets --all-features --workspace -- -D warnings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-src, clippy, rustfmt

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
