name: Continuous Integration

on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-src, clippy, rustfmt

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: Install ldproxy
        run: cargo install ldproxy

      - name: Run fmt command
        run: cargo fmt --all -- --check --color always

      - name: Run clippy command
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

      - name: Run build command
        run: cargo build --release

      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        if: github.ref_type == 'tag'
        with:
          generateReleaseNotes: "true"
          assets: |
            - path: target/riscv32imc-esp-espidf/release/doorsys-firmware
              name: doorsys-firmware-${{ github.ref_name }}.elf
              label: Version ${{ github.ref_name }}
